Iter9
ajugalushkin/url-shortener-version2 pull request #9
Opened 2024-03-26 18:08 UTC by ajugalushkin

2024-04-03 09:32 UTC, arttet requested changes

2024-04-03 09:32 UTC, arttet commented on internal/handler/handler.go
> +		cfg:     cfg}
CHANGE REQUEST: please format your code.

2024-04-03 09:32 UTC, arttet commented on internal/handler/handler.go
> +	"github.com/ajugalushkin/url-shortener-version2/internal/config"
CHANGE REQUEST: please sort imports

2024-04-03 09:32 UTC, arttet commented on internal/handler/handler.go
> +	body, err := io.ReadAll(context.Request().Body)
CHANGE REQUEST: please move it to the `validate` package

2024-04-03 09:32 UTC, arttet commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
CHANGE REQUEST: please don't use global variables

2024-04-03 09:32 UTC, arttet commented on internal/logger/logger.go
> +func RequestLogger(next echo.HandlerFunc) echo.HandlerFunc {
```suggestion
func middlewareLogger(next echo.HandlerFunc) echo.HandlerFunc {
```

2024-04-03 09:32 UTC, arttet commented on internal/model/json.go
> +package model
```suggestion
package dto
```

2024-04-03 09:32 UTC, arttet commented on internal/storage/file_storage.go
> +type FileStorage struct {
CHANGE REQUEST: it shouldn't be a file storage.

2024-04-06 08:19 UTC, closed without merging

2024-04-07 06:10 UTC, ajugalushkin commented
Reopen pull request

2024-04-07 06:10 UTC, ajugalushkin commented
Reopen pull request